title: myFB
subtitle: 自己的图床
description: >
  myFB 可以把你的百度存储变成你的个人图床,
  点击右上角然后使用你的百度帐号登陆就能使用.
  在保证图片和谐并且授权有效的情况下图片有效期应该能有一年,
  一年后需要在本网站重新使用百度帐号登陆一次.
  <p/>
  注意:这个分享可能暴露你的百度云上本应用的操作权限,
  所以推荐只做一些简单的图片分享.
  <p/>
  <a href='https://github.com/dbsGen/myFB'>Source code</a>